### ISSUE TITLE
don't emit change if data hasn't changed

### ISSUE THREAD

**Issue by edge** [edge/fluxette#1]
Where should this go? Several options include:

1. In the Store: if no actions are processed (i.e. actions === undefined or nothing happens in actions.forEach), set an 'unchanged' property on the store. I don't like putting properties on functions. Putting it on the state would feel hackish and half-baked.

2. Recursively do a comparison on each Store with its previous result, but that feels redundant and slow.

3. In `shouldComponentUpdate` or `listener`, where it keeps track of current and previous states. However, this will only work for React and it doesn't work well when the store is a primitive, because the specifier must return an object. Since it only really matters in React, maybe we should allow the specifier to return a primitive, and auto-place it on some property on the state, like `state.data` or `state.value`. It's also possible to just do a hard iteration.

I'm mostly for 3, or 2 if necessary.

Any suggestions?

**Comment by edge** [comment]
47bf2abd864dd76aa403ed50af4ac6d01e70feb5 attempts to do it by method 3, and 870002388a82948539346ea15c78f5e4539fe1e0 attempts to do it by method 2, but both are incomplete and each have their flaws.

This is a tough one.

**Comment by sheerun** [comment]
For #2 stores could be instances of `Immutable.Record` and comparison can be done with `===`.

**Comment by edge** [comment]
I've settled with #3 for now. It prevents the rerender if the state was updated and you connected to a Store (leaf), but not a branch. That's fine, since most flux implementations either don't have branches or simply force you to subscribe to a Store.
