### ISSUE TITLE
@connect this.context undefined

### ISSUE THREAD

**Issue by ameensol** [edge/fluxette#13]
Got this error on the server:

```
TypeError: Cannot read property 'flux' of undefined
at new Connect (.../node_modules/fluxette/lib/react/connect.js:54:28)
```

I put two log statements into connect.js as follows:
```js
constructor(...args) {
   console.log('connect args')
   console.log(args)

   console.log('connect this.context')
   console.log(this.context)
   ...
}
```

And it generated this output right before the error:
```
connect args
{ '0': 
   { topic: 
      { id: 30, ... },
  '1': 
   { flux: 
      { init: [Function: init],
        dispatch: [Function: dispatch],
        process: [Function: process],
        update: [Function: update],
        use: [Function: use],
        state: [Function: state],
        history: [Function: history],
        hook: [Function],
        unhook: [Function: unhook] } } }
connect this.context
undefined
TypeError: Cannot read property 'flux' of undefined
```

Abramov says [here](https://github.com/rackt/react-router/issues/975#issuecomment-86865008) that the second arg to constructor is context, which appears to be the case. 

Changing ``let { flux } = this.context`` to ``let flux = args[1].flux`` fixed it.

**Comment by ameensol** [comment]
It may be that this is only an issue for ``react-router`` integration.

**Comment by ameensol** [comment]
Actually I'm getting ``undefined`` for ``this.context`` in the calls to ``@connect`` for my other components as well. Maybe I'm doing something wrong with the context?

**Comment by edge** [comment]
Fixed in fluxette-react.
